## Numpy
### work with arrays, matrices and perform mathematical ops

In [89]:
import numpy as np

### Create Array

In [90]:
arr = np.array([1, 2, 3, 4, 5])
print("Array : ", arr)
print("Array type: ", str(type(arr)))
print("Array shape: ", str(arr.shape))
print("Array dtype: ", str(arr.dtype))
print("Array ndim: ", str(arr.ndim))
print("Array size: ", str(arr.size))
print("Array itemsize: ", str(arr.itemsize))
print("Reshaped Array (5, 1): \n", str(arr.reshape(5, 1)))

Array :  [1 2 3 4 5]
Array type:  <class 'numpy.ndarray'>
Array shape:  (5,)
Array dtype:  int64
Array ndim:  1
Array size:  5
Array itemsize:  8
Reshaped Array (5, 1): 
 [[1]
 [2]
 [3]
 [4]
 [5]]


In [91]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print("Array: \n", arr)
print("Array shape: ", str(arr.shape))
print("Array dtype: ", str(arr.dtype))
print("Array ndim: ", str(arr.ndim))
print("Array size: ", str(arr.size))
print("Array itemsize: ", str(arr.itemsize))
print("Reshaped Array (3, 2): \n", str(arr.reshape(3, 2)))

Array: 
 [[1 2 3]
 [4 5 6]]
Array shape:  (2, 3)
Array dtype:  int64
Array ndim:  2
Array size:  6
Array itemsize:  8
Reshaped Array (3, 2): 
 [[1 2]
 [3 4]
 [5 6]]


## Inbuilt functions

In [92]:
# start,stop,step
arr = np.arange(1, 10, 2)
print("Array with arange: ", arr)

# shape
arr = np.ones((5, 2))
print("Array with ones: \n", arr)

# shape
arr = np.zeros((3, 4))
print("Array with zeros: \n", arr)

# shape
arr = np.eye(3,2)
print("Identity matrix: \n", arr)

Array with arange:  [1 3 5 7 9]
Array with ones: 
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
Array with zeros: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Identity matrix: 
 [[1. 0.]
 [0. 1.]
 [0. 0.]]


### Math ops

In [93]:
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([6, 7, 8, 9, 10])
print("Addition: ", arr1 + arr2)
print("Subtraction: ", arr1 - arr2)
print("Multiplication: ", arr1 * arr2)
print("Division: ", arr1 / arr2)

Addition:  [ 7  9 11 13 15]
Subtraction:  [-5 -5 -5 -5 -5]
Multiplication:  [ 6 14 24 36 50]
Division:  [0.16666667 0.28571429 0.375      0.44444444 0.5       ]


In [94]:
arr = np.array([4, 9, 16, 25])
print("Square root: ", np.sqrt(arr))
print("Exponential: ", np.exp(arr))
print("Logarithm: ", np.log(arr))
print("Sin: ", np.sin(arr))

Square root:  [2. 3. 4. 5.]
Exponential:  [5.45981500e+01 8.10308393e+03 8.88611052e+06 7.20048993e+10]
Logarithm:  [1.38629436 2.19722458 2.77258872 3.21887582]
Sin:  [-0.7568025   0.41211849 -0.28790332 -0.13235175]


In [95]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print("Sum: ", np.sum(arr))
print("Mean: ", np.mean(arr))
print("Median: ", np.median(arr))
print("Standard Deviation: ", np.std(arr))
print("Variance: ", np.var(arr))
print("Max: ", np.max(arr))
print("Min: ", np.min(arr))

# Vertical
print("Sum along axis 0: ", np.sum(arr, axis=0))
# Horizontal
print("Sum along axis 1: ", np.sum(arr, axis=1))

Sum:  21
Mean:  3.5
Median:  3.5
Standard Deviation:  1.707825127659933
Variance:  2.9166666666666665
Max:  6
Min:  1
Sum along axis 0:  [5 7 9]
Sum along axis 1:  [ 6 15]


## Slicing

In [96]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Original Array: \n", arr)
print("Sliced Array (rows 0, cols 0): \n", arr[0, 0])
print("Sliced Array (rows 0-1, cols 1-2): \n", arr[0:2, 1:3])
print("Sliced Array (rows 1-2, all cols): \n", arr[1:3, :])
print("Sliced Array (all rows, cols 0-1): \n", arr[:, 0:2])

Original Array: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Sliced Array (rows 0, cols 0): 
 1
Sliced Array (rows 0-1, cols 1-2): 
 [[2 3]
 [5 6]]
Sliced Array (rows 1-2, all cols): 
 [[4 5 6]
 [7 8 9]]
Sliced Array (all rows, cols 0-1): 
 [[1 2]
 [4 5]
 [7 8]]


### Indexing

In [97]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(arr > 5)
print(arr[arr > 5])
print(arr[(arr >= 5) & (arr <= 8)])

[False False False False False  True  True  True  True  True]
[ 6  7  8  9 10]
[5 6 7 8]
